# Generated by Django 3.0.8 on 2020-07-10 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('text_signup', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipient',
            name='i_consent',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
