# Generated by Django 3.0.8 on 2020-07-10 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('text_signup', '0002_recipient_i_consent'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipientselection',
            name='n_frequency',
            field=models.CharField(default='D', max_length=1),
            preserve_default=False,
        ),
    ]
