# Generated by Django 3.0.8 on 2020-07-10 19:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('text_signup', '0003_recipientselection_n_frequency'),
    ]

    operations = [
        migrations.CreateModel(
            name='Frequency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n_order', models.SmallIntegerField()),
                ('t_frequency', models.CharField(max_length=15)),
            ],
        ),
        migrations.AlterField(
            model_name='recipientselection',
            name='n_frequency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='text_signup.Frequency'),
        ),
    ]
