# Generated by Django 3.0.8 on 2020-07-10 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('text_signup', '0004_auto_20200710_2149'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipient',
            name='t_phone_number',
        ),
        migrations.AddField(
            model_name='recipient',
            name='t_phone_area_code',
            field=models.CharField(default='G', max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recipient',
            name='t_phone_line_code',
            field=models.CharField(default='G', max_length=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recipient',
            name='t_phone_local_code',
            field=models.CharField(default='G', max_length=3),
            preserve_default=False,
        ),
    ]
