# Generated by Django 3.0.8 on 2020-07-10 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('text_signup', '0005_auto_20200710_2241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='state',
            name='t_state',
            field=models.CharField(max_length=20),
        ),
    ]
