# Generated by Django 3.0.8 on 2020-07-11 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('text_signup', '0006_auto_20200710_2309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='county',
            name='t_county',
            field=models.CharField(max_length=35),
        ),
    ]
