# Generated by Django 3.0.8 on 2020-07-18 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('text_signup', '0016_auto_20200717_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipient',
            name='t_email_address',
            field=models.CharField(max_length=256, unique=True),
        ),
        migrations.AlterField(
            model_name='recipient',
            name='t_phone_area_code',
            field=models.CharField(help_text='Area code or first 3 digits of phone number', max_length=3),
        ),
        migrations.AlterField(
            model_name='recipient',
            name='t_phone_line_code',
            field=models.CharField(help_text='Line code or last 4 digits of phone number', max_length=4),
        ),
        migrations.AlterField(
            model_name='recipient',
            name='t_phone_local_code',
            field=models.CharField(help_text='Local code or second 3 digits of phone number', max_length=3),
        ),
    ]
