# Generated by Django 3.0.8 on 2020-07-20 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('text_signup', '0017_auto_20200718_1100'),
    ]

    operations = [
        migrations.AddField(
            model_name='frequency',
            name='q_end_days_back',
            field=models.SmallIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='frequency',
            name='q_start_days_back',
            field=models.SmallIntegerField(default=1),
            preserve_default=False,
        ),
    ]
