# Generated by Django 3.0.8 on 2020-07-20 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('text_signup', '0018_auto_20200720_2128'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='frequency',
            name='q_end_days_back',
        ),
        migrations.RemoveField(
            model_name='frequency',
            name='q_start_days_back',
        ),
    ]
