# Generated by Django 3.0.8 on 2020-07-23 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('text_signup', '0019_auto_20200720_2131'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipient',
            name='t_phone_country_code',
            field=models.CharField(default='+1', help_text='Leading + sign, followed by the country code for the number', max_length=4),
            preserve_default=False,
        ),
    ]
