# Generated by Django 3.0.8 on 2020-07-23 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('text_signup', '0020_recipient_t_phone_country_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipient',
            name='t_phone_country_code',
            field=models.CharField(default='+1', help_text='Leading + sign, followed by the country code for the number', max_length=4),
        ),
    ]
