# Generated by Django 3.0.8 on 2020-07-27 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('text_signup', '0023_location'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='county',
            options={'ordering': ['t_county']},
        ),
        migrations.AlterModelOptions(
            name='state',
            options={'ordering': ['t_state']},
        ),
    ]
