# Generated by Django 3.0.8 on 2020-07-28 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('text_signup', '0024_auto_20200727_2208'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='recipient',
            unique_together={('t_phone_country_code', 't_phone_area_code', 't_phone_local_code', 't_phone_line_code')},
        ),
    ]
