# Generated by Django 3.0.8 on 2020-07-12 19:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('text_signup', '0013_auto_20200711_2205'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyCountyKnownCases',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('d_date', models.DateField()),
                ('q_cases', models.SmallIntegerField()),
                ('n_county', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='text_signup.County')),
            ],
        ),
        migrations.CreateModel(
            name='DailyCountyDeaths',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('d_date', models.DateField()),
                ('q_deaths', models.SmallIntegerField()),
                ('n_county', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='text_signup.County')),
            ],
        ),
    ]
