# Generated by Django 3.0.8 on 2020-07-17 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_pull', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailycountydeaths',
            name='q_deaths',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='dailycountyknowncases',
            name='q_cases',
            field=models.IntegerField(),
        ),
    ]
