# Generated by Django 3.0.8 on 2020-07-19 06:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('text_signup', '0017_auto_20200718_1100'),
        ('data_pull', '0002_auto_20200717_1453'),
    ]

    operations = [
        migrations.CreateModel(
            name='SummaryCountyKnownCases',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('d_updated', models.DateField()),
                ('q_cases_change', models.IntegerField()),
                ('q_total_cases', models.IntegerField()),
                ('n_county', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='text_signup.County')),
                ('n_frequency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='text_signup.Frequency')),
            ],
        ),
    ]
