# Generated by Django 3.0.8 on 2020-07-19 07:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('text_signup', '0017_auto_20200718_1100'),
        ('data_pull', '0005_auto_20200719_0916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='summarycountyknowncases',
            name='n_county',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='text_signup.County'),
        ),
        migrations.AlterField(
            model_name='summarycountyknowncases',
            name='n_frequency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='text_signup.Frequency'),
        ),
    ]
