# Generated by Django 3.0.8 on 2020-07-20 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('text_signup', '0017_auto_20200718_1100'),
        ('data_pull', '0006_auto_20200719_0917'),
    ]

    operations = [
        migrations.CreateModel(
            name='SummaryByCountyFrequency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('d_updated', models.DateField()),
                ('q_cases_change', models.IntegerField()),
                ('q_total_cases', models.IntegerField()),
                ('q_deaths_change', models.IntegerField()),
                ('q_total_deaths', models.IntegerField()),
                ('n_county', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='text_signup.County')),
                ('n_frequency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='text_signup.Frequency')),
            ],
        ),
        migrations.CreateModel(
            name='SummaryByStateFrequency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('d_updated', models.DateField()),
                ('q_cases_change', models.IntegerField()),
                ('q_total_cases', models.IntegerField()),
                ('q_deaths_change', models.IntegerField()),
                ('q_total_deaths', models.IntegerField()),
                ('n_frequency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='text_signup.Frequency')),
                ('n_state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='text_signup.State')),
            ],
        ),
        migrations.DeleteModel(
            name='SummaryCountyKnownCases',
        ),
    ]
