# Generated by Django 3.0.8 on 2020-07-27 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_pull', '0007_auto_20200720_2118'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SummaryByStateFrequency',
        ),
    ]
